#!/bin/bash

sudo modprobe v4l2loopback exclusive_caps=1

device=$(v4l2-ctl --list-devices | grep Dummy -A 1 | grep 'video[0-9]')

res=$(xrandr | grep ' connected ' | grep -v primary | awk '{print $3}' | awk -F '+' '{print $1}')

pos=$(xrandr | grep ' connected ' |grep -v primary | awk '{print $3}' | awk -F '+' '{print $2}')

ffmpeg -f x11grab -r 15 -s $res -i :0.0+$pos,0 -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 $device
